name: Prettier Format

on:
  pull_request:
    branches:
      - master

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Para tener historial completo y evitar problemas de merge

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run format

      - name: Check for file changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Files were modified by Prettier";
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add .
            git commit -m "Format code with Prettier"
          else
            echo "No changes to commit"
          fi

      - name: Push changes
        if: success() && steps.commit.outputs.committed == 'true'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
